/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioDhartiPanchalRouteImport } from './routes/portfolio.dharti-panchal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDhartiPanchalRoute = PortfolioDhartiPanchalRouteImport.update({
  id: '/portfolio/dharti-panchal',
  path: '/portfolio/dharti-panchal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio/dharti-panchal': typeof PortfolioDhartiPanchalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio/dharti-panchal': typeof PortfolioDhartiPanchalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio/dharti-panchal': typeof PortfolioDhartiPanchalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portfolio/dharti-panchal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portfolio/dharti-panchal'
  id: '__root__' | '/' | '/portfolio/dharti-panchal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioDhartiPanchalRoute: typeof PortfolioDhartiPanchalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/dharti-panchal': {
      id: '/portfolio/dharti-panchal'
      path: '/portfolio/dharti-panchal'
      fullPath: '/portfolio/dharti-panchal'
      preLoaderRoute: typeof PortfolioDhartiPanchalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioDhartiPanchalRoute: PortfolioDhartiPanchalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
